package com.example.demo.Table

class BannerImages {
    companion object {
        val TABLE_NAME="BannerImages"
        const val BiImgNo = "bi_imgno"
        const val BiServID = "bi_serid"
        const val BiImage = "bi_image"
        var deleteKeys = arrayListOf(BiImgNo)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(BiImgNo)

        var primaryKeys = arrayListOf(BiImgNo)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
    }