package com.example.demo.Table

class CustomerPayment {

    companion object {
        const val cpID = "cp_id"
        const val cpCustID = "cp_custId"
        const val cpPaymentType = "cp_paymentType"
        const val cpServID = "cp_servId"
        const val cpStID = "cp_stId"
        const val cpPymtNo = "cp_pymtno"
        const val cpAmtPaid = "cp_amtpaid"
        const val cpPymtDate = "cp_pymtDate"
        const val cpPymtMethod = "cp_pymtMethod"
        const val cpCheckNo = "cp_checkno"
        const val cpPymtRefNo = "cp_pymtRefno"
        const val cpPymtIssuingBank = "cp_pymtIssuingBank"
        const val cpCreatedBy = "cp_createdBy"
        const val cpCreatedDateTime = "cp_createdDateTime"
        const val cpUpdatedBy = "cp_updatedBy"
        const val cpUpdatedDateTime = "cp_updatedDateTime"
        const val cpIsActive = "cp_isActive"
        const val cpPaystatus = "cp_paystatus"

        var deleteKeys = arrayListOf(cpID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(cpID)

        var primaryKeys = arrayListOf(cpID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
    }
