package com.example.demo.Table

import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.web.bind.annotation.CrossOrigin
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

class Customer_Documents {
    companion object {
        const val CDCustID="cd_custId"
        const val CDSLNO="cd_slno"
        const val CDTitle="cd_title"
        const val CDImage="cd_image"
        const val CDCreatedBy="cd_createdBy"
        const val CDCreatedDateTime="cd_createdDateTime"
        const val CDUpdatedBy="cd_updatedBy"
        const val CDUpdatedDateTime="cd_updatedDateTime"
        const val CDIsActive="cd_isActive"

        var deleteKeys = arrayListOf(CDSLNO)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(CDSLNO)

        var primaryKeys = arrayListOf(CDSLNO)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
    }


//Services

class CustomerDocumentWS()
{

}