package com.example.demo.Table

class CustomerMemServices {
    companion object
    {
        const val cmsID="cms_id"
        const val cmsCustID="cms_custid"
        const val cmsPlanID="cms_planid"
        const val cmServID="cms_servid"
        const val cmsServmaxInstance="cms_Servmaxinstances"
        const val cmsCreatedBy="cms_createdBy"
        const val cmsCreatedDateTime="cms_createdDateTime"
        const val cmsUpdatedBy="cms_updatedBy"
        const val cmsUpdatedDateTime="cms_updatedDateTime"
        const val cmsIsActive="cms_isActive"

        var deleteKeys = arrayListOf(cmsID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(cmsID)

        var primaryKeys = arrayListOf(cmsID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }

}