package com.example.demo.Table

class HelpLine {
    companion object
    {
        val TABLE_NAME = "helpline"
        const val ID="id"
        const val housingSociety="housing_society"
        const val helplineCategory="helpline_category"
        const val SrNo="sr_no"
        const val Title="title"
        const val contactNumber="contact_number"
        var deleteKeys = arrayListOf(ID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(ID)

        var primaryKeys = arrayListOf(ID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
    }
