package com.example.demo.Table

import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.web.bind.annotation.CrossOrigin
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

class Lovs {
    companion object {
        val TABLE_NAME = "lovs"
        const val lovType="lov_type"
        const val lovStoreValue="lov_storeValue"
        const val lovDisplayValue="lov_displayValue"
        const val lovSortingOrder="lov_sortingOrder"
        const val lovURL="lov_url"
        const val lovImage="lov_image"
        const val lovCreatedBy="lov_createdBy"
        const val lovCreatedDateTime="lov_createdDateTime"
        const val lovUpdatedBy="lov_updatedBy"
        const val lovUpdatedDateTime="lov_updatedDateTime"
        const val lovIsActive="lov_isActive"
        const val lovInternal="lov_internal"
        var deleteKeys = arrayListOf(lovStoreValue)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(lovStoreValue)

        var primaryKeys = arrayListOf(lovStoreValue)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
}


//Services
class LovWS()
{

}
