package com.example.demo.Table

class MembershipPlan {
    companion object {
        const val mpID = "mp_Id"
        const val mpIitle = "mp_title"
        const val mpDescription = "mp_description"
        const val mpImage = "mp_image"
        const val mpFees = "mp_fees"
        const val mpnbrOfmonths = "mp_nbrOfMonths"
        const val mpCreatedBy = "mp_createdBy"
        const val mpCreateDateTime = "mp_createdDateTime"
        const val mpUpdatedBy = "mp_updatedBy"
        const val mpUpdatedDateTime = "mp_updatedDateTime"
        const val mpIsActive = "mp_isActive"

        var deleteKeys = arrayListOf(mpID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(mpID)

        var primaryKeys = arrayListOf(mpID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }

}