package com.example.demo.Table

import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.web.bind.annotation.CrossOrigin
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

class MembershipPlanServices
{
    companion object
    {
         val TABLE_NAME="membership_plan"
        const val mpsId="mps_id"
        const val mpsCatId="mps_catid"
        const val mpsServiceId="mps_serviceid"
        const val mpsMaxInstances="mps_maxInstances"
        const val mpsCreatedBy="mps_createdBy"
        const val mpsCreatedDateTime="mps_createdDateTime"
        const val mpsUpdatedBy="mps_updatedBy"
        const val mpsUpdatedDateTime="mps_updatedDateTime"
        const val mpsIsActive="mps_isActive"

        var deleteKeys = arrayListOf(mpsId)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(mpsId)

        var primaryKeys = arrayListOf(mpsId)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
    }


//services
class MemPlanServiceWS()
{

}