package com.example.demo.Table

class Notification {
    companion object
    {
        const val ID="id"
        const val DeviceID="device_id"
        const val CustID="cust_id"
        const val TransID="trans_id"
        const val Message="message"
        const val Type="type"
        const val Flag="flag"
        const val CreatedAt="created_at"
        const val UpdatedAt="updateda_at"

        var deleteKeys = arrayListOf(ID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(ID)

        var primaryKeys = arrayListOf(ID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
}
