package com.example.demo.Table

class ServiceProblem {
    companion object
    {
        val TABLE_NAME="service_problems"
        const val ID="sp_Id"
        const val SrvID="sp_srvId"
        const val ProblemNo="sp_problemNo"
        const val Title="sp_title"
        const val Description="sp_description"
        const val Image="sp_image"
        const val CreatedBy="sp_createdBy"
        const val CreatedDateTime="sp_createdDateTime"
        const val UpdatedBy="sp_updatedBy"
        const val UpdatedDateTime="sp_updatedDateTime"
        const val IsActive="sp_isActive"

        var deleteKeys = arrayListOf(ID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(ID)

        var primaryKeys = arrayListOf(ID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
    }
