package com.example.demo.Table

class ServicesFaqs
{
    companion object
    {
        val TABLE_NAME="service_faqs"
        const val SFID="sf_Id"
        const val SFsrvID="sf_srvId"
        const val SFQuestionNo="sf_questionNo"
        const val SFSortingOrder="sf_sortingOrder"
        const val SFQuestion="sf_question"
        const val SFAnswer="sf_answer"
        const val SFCreatedBy="sf_createdBy"
        const val SFCreatedDateTime="sf_createdDateTime"
        const val SFUpdatedBy="sf_updatedBy"
        const val SFUpdatedDateTime="sf_updatedDateTime"
        const val SFIsActive="sf_isActive"

        var deleteKeys = arrayListOf(SFID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(SFID)

        var primaryKeys = arrayListOf(SFID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
    }
