package com.example.demo.Table

class ServiceTxnLog {
    companion object
    {
        val TABLE_NAME="servicetxn_log"
        const val STLID="stl_id"
        const val STLstID="stl_stid"
        const val STLStatus="stl_status"
        const val STLCreatedBy="stl_createdBy"
        const val STLCreatedDateTime="stl_createdDateTime"

        var deleteKeys = arrayListOf(STLID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(STLID)

        var primaryKeys = arrayListOf(STLID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
    }