package com.example.demo.Table

import com.example.demo.Extensions.*
import com.example.demo.RESPONSE_TECH_ERROR
import org.json.JSONArray
import org.json.JSONObject
import org.springframework.boot.Banner
import org.springframework.web.multipart.MultipartFile
import java.sql.PreparedStatement
import java.util.*
import java.util.concurrent.atomic.AtomicInteger
import kotlin.collections.ArrayList

class ServiceCategory {
    companion object
    {
        val TABLE_NAMEONE="Service"
        val TABLE_NAME="ServiceCategory"
        const val CatID="sc_catId"
        const val CatName="sc_catName"
        const val Description="sc_description"
        const val CatImage="sc_catImage"
        const val CreatedBy="sc_createdBy"
        const val CreatedDateTime="sc_createdDateTime"
        const val UpdatedBy="sc_updatedBy"
        const val UpdatedDateTime="sc_updatedDateTim"
        const val ISActive="sc_isActive"

        var deleteKeys = arrayListOf(CatID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(CatID)

        var primaryKeys = arrayListOf(CatID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
    }

class ServiceCategaryWS()
{

    fun getServiceCatBannerImage (
            id: Int
    ):String
    {
        var conn= getDBConnection()

        var IsBaseSQL=" FROM ${ServiceCategory.TABLE_NAME} a INNER JOIN ${BannerImages.TABLE_NAME} b" +
                " ON a.${ServiceCategory.CatID}=b.${BannerImages.BiImgNo}"

        var IsSQL="SELECT a.*,b.*"

        var IsWhere=""

        if (id>0)
        {
            IsWhere=IsWhere + " WHERE ${ServiceCategory.CatID}='$id'"
        }

        var IsFinal=IsSQL + IsBaseSQL + IsWhere

        var jsonArray= rowsToJsonArray(IsFinal,conn!!)

        var stmt=conn!!.createStatement()
        var rs=stmt.executeQuery(IsFinal)

        var JSONResult=JSONObject().apply {
            put ("DATA",jsonArray)
            put("Status",DBFunctions.SUCCESS)
            put("SQL",IsFinal)
        }
        conn?.close()
        return JSONResult.toString()


    }


    fun getServiceCat(
            id: Int
    ):String{
        var conn= getDBConnection()

        var IsBaseSQL=" FROM ${ServiceCategory.TABLE_NAME} a INNER JOIN ${Service.TABLE_NAME} b" +
                " ON a.${ServiceCategory.CatID} = b.${Service.SRVCATID}"

        var IsSQL="SELECT a.*,b.*"

        var IsWhere=""

        if (id>0)
        {
            IsWhere= IsWhere + " WHERE ${ServiceCategory.CatID}='$id'"
        }

        var IsFinal=IsSQL + IsBaseSQL + IsWhere

        var jsonArray = rowsToJsonArray(IsFinal,conn!!)

        var stmt=conn!!.createStatement()
        var rs=stmt.executeQuery(IsFinal)

        var JSONRESULT=JSONObject().apply {
            put("DATA",jsonArray )
            put("STATUS", DBFunctions.SUCCESS)
            put("SQL", IsFinal)
        }

        conn!!.close()

        return JSONRESULT.toString()

    }


    fun postServiceCat(
            name: String,
            description: String,
            image: MultipartFile
    ):String
    {
        var lsMsg=""
        var active='Y'
        var conn= getDBConnection()
        conn!!.autoCommit=false

        lateinit var prepareStatement:PreparedStatement
        var sqlStatement=ArrayList<SQLModel>()


        //Image File
        var fileName=""
        if (image!=null)
        {
            if (image.isEmpty.not())
            {
                var filePath=Validation().getPath()
                val uuid= UUID.randomUUID()
                fileName="data:image/jpeg;base64,/9j/"+uuid+".png"
            }
            else
            {
                return fileName
            }
        }

        //validation
        var msg = "Validation Error"
        val namevalidation = Validation().maxRangeValidation(name)
        val descriptionvalidation = Validation().maxRangeValidation(description)

        var validationDone: Boolean = true
        if (!namevalidation) {

            Validation().genMsg("Name should not be greater than 255 char")
            validationDone = false
        }
        if (!descriptionvalidation) {

            Validation().genMsg("Name should not be greater than 255 char")
            validationDone = false
        }
        if (!validationDone && lsMsg.length > 0) {

            var ErroRes = Validation().validationMsg(lsMsg)
            return ErroRes.toString()
        }

        //For Auto-generating Cust-ID
        val atomicInteger = AtomicInteger()
        var catID = atomicInteger.getAndIncrement()


        var checkObject = JSONObject().apply {
                 put(ServiceCategory.CatID,catID)
            put(ServiceCategory.CatName,name)
            put(ServiceCategory.Description,description)
            put(ServiceCategory.CatImage,fileName)
            put(ServiceCategory.ISActive,active)
        }

        try {
            var jsonArray = JSONArray()
            jsonArray.put(checkObject)
            var insert = jsonInsert(jsonArray, ServiceCategory.TABLE_NAME, conn!!)

            for (i in 0 until insert.size) {
                sqlStatement.add(insert[i])
            }

            try {
                for (i in 0 until sqlStatement.size) {
                    var e = sqlStatement[i]
                    var preparedStatement = conn!!.prepareStatement(e.statement)
                    preparedStatement.executeUpdate()
                }
                conn!!.commit()
            } catch (e: Exception) {
                conn!!.rollback()
                conn!!.close()

                var jsonResponse = getResponseData(RESPONSE_TECH_ERROR, e.toString())
            }
        } catch (e: java.lang.Exception) {
            conn?.rollback()
            return Validation().getStatusMessage("Failed", "Error while inserting data".plus("${e.message}"))
        } finally {
            conn?.close()
        }
        return Validation().getStatusMessage("Success", "Record inserted successully")

    }


    fun editServiceCat(
            id:Int,
            name:String,
            description:String,
            image:MultipartFile

    ):String{
        var IsMsg=""
        var active='Y'
        var IsSql=""

        var conn= getDBConnection()
        conn!!.autoCommit=false

        lateinit var prepareStatement:PreparedStatement
        var sqlStatement=ArrayList<SQLModel>()

        var fileName=""
        if (image!=null)
        {
            if (image.isEmpty.not())
            {
                var filePath=Validation().getPath()
                val uuid=UUID.randomUUID()
                fileName="data:image" + uuid+ ".png"
            }
        }

        //validation
        val namevalidation= Validation().maxRangeValidation(name)
        val descriptionvalidation=Validation().maxRangeValidation(description)
       if(!namevalidation)
       {
           Validation().genMsg("Name should not be greater than 255 character")
       }

        if (!descriptionvalidation)
        {
            Validation().genMsg("description should not be greater than 255 character")
        }

        var validationDone: Boolean = true

        if (!validationDone && IsMsg.length>0)
        {
            var Errorres=Validation().validationMsg(IsMsg)
            return Errorres.toString()
        }


        var IsBaseSQL= " SET sc_catName='${name}'" +
                              " OR" +
                              " sc_description= '${description}" +
                              " OR" +
                              " sc_catImage='${fileName}'"

        var IsSQL="UPDATE ${ServiceCategory.TABLE_NAME}"

        var IsWhere=" "

           if (id>0)
           {
               IsWhere = IsWhere + " WHERE sc_catId = '${id}'"
           }


        var IsFinal=IsSQL + IsBaseSQL + IsWhere

        var count=0
        var lbUpdate=false
        try {

            var checkObject = JSONObject().apply {
                put(ServiceCategory.CatID, id)
                put(ServiceCategory.CatName, name)
                put(ServiceCategory.Description, description)
                put(ServiceCategory.ISActive, active)
                put(ServiceCategory.CatImage, image)
            }

            var jsonArray = JSONArray()
            jsonArray.put(checkObject)

            if (lbUpdate) {
                var insert = jsonUpdate(jsonArray, ServiceCategory.TABLE_NAME)
                for (i in 0 until insert.size) {
                    sqlStatement.add(insert[i])
                    IsSql = insert[i].statement
                }

            } else {
                var insert = jsonInsert(jsonArray, ServiceCategory.TABLE_NAME, conn!!)
                for (i in 0 until insert.size) {
                    sqlStatement.add(insert[i])
                }
//            var ps=conn.prepareStatement(IsFinal)
//            count=ps.executeUpdate()
            }
            if(conn!=null)
            {
                try {
                   for (i in 0 until sqlStatement.size)
                   {
                       var e = sqlStatement[i]
                       var prepareStatement=conn!!.prepareStatement(e.statement)
                       prepareStatement.execute()

                   }
                    conn!!.commit()
                }
                catch (e:Exception)
                {
                       conn?.rollback()
                    conn?.close()
                    var jsonResponses = getResponseData(RESPONSE_TECH_ERROR,e.toString())
                    return jsonResponses.toString()
                }
                 finally {
                     conn?.close()
                 }
            }
        }
        catch (e:Exception)
        {
          conn?.rollback()

            return Validation().getStatusMessage("Failed","Error while updating record".plus("${e.message}")).toString()
        }
        finally {
            conn?.close()
        }

        return Validation().getStatusMessage("Success","Record updated successfully")

    }


    fun deleteServiceCat(
            id:Int
    ):String{

          var conn= getDBConnection()

        var IsSQL=" SELECT count(1) dataCount " +
                " FROM ${ServiceCategory.TABLE_NAME}"
                " WHERE ${ServiceCategory.CatID}='$id'"

        var stmt=conn!!.createStatement()

        var rs=stmt.executeQuery(IsSQL)

        var totalRows=0

        while (rs!!.next())
        {
            totalRows=rs.getNullableInt("dataCount")!!
        }

        var IsBaseSQL=" FROM ${ServiceCategory.TABLE_NAME} a LEFT JOIN ${Service.TABLE_NAME} b" +
                      " ON a.${ServiceCategory.CatID} = b.${Service.SRVCATID}"


         IsSQL="DELETE a.*,b.*"

        var IsWHERE=""

        if(id>0)
        {
            IsWHERE=" WHERE ${ServiceCategory.CatID}='$id'"
        }

        var IsFinal=IsSQL + IsBaseSQL  + IsWHERE

        var count= execUpdate(conn!!,IsFinal)

        return Validation().getStatusMessage("Success","Record deleted successfully")
    }


}