package com.example.demo.Table

class ServiceTransaction {
    companion object
    {
        val TABLE_NAME="service_transaction"
        const val STID   ="st_id"
        const val STCustID   ="st_custId"
        const val STServID   ="st_servId"
        const val STProblemNo   ="st_problemNo"
        const val STProblemDesc   ="st_problemDesc"
        const val STPrefDate   ="st_prefDate"
        const val STPrefTime   ="st_prefTime"
        const val STPrefendTime   ="st_prefEndTime"
        const val  STStatus   ="st_status"
        const val STCancelledState   ="st_cancelledState"
        const val STCreatedBy   ="st_createdBy"
        const val STCreateDateTime   ="st_createdDateTime"
        const val  STUpdatedBy   ="st_updatedBy"
        const val STUpdatedDateTime   ="st_updatedDateTime"
        const val  STIsActive   ="st_isActive"
        const val  STIsPaid   ="st_isPaid"

        var deleteKeys = arrayListOf(STID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(STID)

        var primaryKeys = arrayListOf(STID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
    }
