package com.example.demo.Table

class SevicetxnFeedback {
    companion object{
        const val STFID="stf_id"
        const val STFstID="stf_stid"
        const val STFcustID="stf_custid"
        const val STFRating="stf_rating"
        const val STFFeedback="stf_feedback"
        const val STFGivenDate="stf_givenDate"
        const val STFIsApproved="stf_isApproved"
        const val STFIsTestimonial="stf_isTestimonial"

        var deleteKeys = arrayListOf(STFID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(STFID)

        var primaryKeys = arrayListOf(STFID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
    }
