package com.example.demo.Table

class TechnicianAvailability {
    companion object
    {
        val TABLE_NAME="technician_availability"
        const val  TAID="ta_id"
        const val  TechID="tech_id"
        const val  TADayofWeek="ta_dayofweek"
        const val  TAStartTime="ta_starttime"
        const val  TAEndTime="ta_endtime"
        const val  TACreatedBy="ta_createdby"
        const val  TACreatedDateTime="ta_createdDateTime"
        const val  TAUpdatedBy="ta_updatedby"
        const val  TAUPdatedDateTime="ta_updatedDateTime"
        const val  TAIsActive="ta_isactive"

        var deleteKeys = arrayListOf(TAID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(TAID)

        var primaryKeys = arrayListOf(TAID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }
}
