package com.example.demo.Table

class Vendor {
    companion object
    {
        val TABLE_NAME="vendor"
        const val VNID="vn_id"
        const val VNTitle="vn_title"
        const val VNDescription="vn_description"
        const val VNIcon="vn_icon"
        const val VNFirstName="vn_firstName"
        const val VNLastName="vn_lastName"
        const val VNMobileNo="vn_mobileNo"
        const val VNAlternateMobileNo="vn_alternateMobileNo"
        const val VNRedirectURL="vn_redirecturl"
        const val VNCreatedBy="vn_createdBy"
        const val VNCreatedDateTime="vn_createdDateTime"
        const val VNUpdatedBy="vn_updatedBy"
        const val VNUpdatedDateTime="vn_updatedDateTime"
        const val VNIsActive="vn_isActive"
        var deleteKeys = arrayListOf(VNID)
        var generatePrimaryKey = true

        var autoGeneratedColumn = arrayListOf(VNID)

        var primaryKeys = arrayListOf(VNID)

    }

    fun getDeleteKeys(): ArrayList<String> {
        return deleteKeys
    }

    fun getPKKeys(): ArrayList<String> {
        return primaryKeys
    }


    fun shouldGeneratePK(): ArrayList<Boolean> {
        val al = ArrayList<Boolean>()
        al.add(generatePrimaryKey)
        return al
    }


    fun getAutoGeneratedColumnName(): ArrayList<String> {
        return autoGeneratedColumn
    }

}